### PR TITLE
#648 Callback not called on lambda handler if notify returns false

### PR DESCRIPTION
**Pull request by subzero10**
## Status
**READY**

## Description
Our lambda handler implementation relies on `afterNotify` to call `callback(err)`.
`afterNotify` will not be called if the precondition checks fail in `notify()`.
Please see [ticket](https://github.com/honeybadger-io/honeybadger-js/issues/648) for more details.

## Related PRs
n/a

## Todos
- [x] Fix bug
- [x] Tests 
- [x] Changelog Entry (unreleased)

## Steps to Test or Reproduce
Create a lambda handler and test without providing an apiKey.
More info on this [ticket](https://github.com/honeybadger-io/honeybadger-js/issues/648).

### CODE REVIEW

**Review by joshuap — APPROVED** [review]
This looks good to me @subzero10, thanks!

One question—do you think that we should be calling the `beforeNotify` and `afterNotify` handlers in the `Honeybadger.notify` function itself if the preconditions fail? i.e., are users expecting the callbacks to run even if an error is not reported?

I think we could ship this fix either way, I'm just curious if this is something we should revisit in the future.

**Comment by joshuap** [comment]
> > This looks good to me @subzero10, thanks!
> > One question—do you think that we should be calling the `beforeNotify` and `afterNotify` handlers in the `Honeybadger.notify` function itself if the preconditions fail? i.e., are users expecting the callbacks to run even if an error is not reported?
> > I think we could ship this fix either way, I'm just curious if this is something we should revisit in the future.
> 
> That's a good question. I think I'm leaning towards not calling them:
> 
> * If the preconditions fail -> don't call `beforeNotify` nor `afterNotify`
> * if `beforeNotify` returns `false` -> don't call `afterNotify`
> 
> I'm not sure I understand this:
> 
> > are users expecting the callbacks to run even if an error is not reported?
> 
> Are you referring to the `beforeNotify` and `afterNotify` callbacks? Or the `lambdaHandler` callback? I think it's OK to assume that users should not expect `beforeNotify` and `afterNotify` to be called if the report is not going to be sent. However, I think they expect the lambda handler's callback to be called in any case (report sent or not), which is what this PR is about.
> 
> What do you think?
> 
> (In any case, I will go ahead and merge this since you approved)

I was referring to the `beforeNotify` and `afterNotify` callbacks—I'm thinking about the case where a user wants to do something similar to what we're doing in `lambdaHandler`—basically "report this error, then do something else, like call a callback." That may not be a super common use case, but it would be more convenient to always call the callbacks in that case, so that the user doesn't have to add an extra conditional (like you did in this PR). 🤷

**Comment by subzero10** [comment]
> > > This looks good to me @subzero10, thanks!
> > > One question—do you think that we should be calling the `beforeNotify` and `afterNotify` handlers in the `Honeybadger.notify` function itself if the preconditions fail? i.e., are users expecting the callbacks to run even if an error is not reported?
> > > I think we could ship this fix either way, I'm just curious if this is something we should revisit in the future.
> > 
> > 
> > That's a good question. I think I'm leaning towards not calling them:
> > 
> > * If the preconditions fail -> don't call `beforeNotify` nor `afterNotify`
> > * if `beforeNotify` returns `false` -> don't call `afterNotify`
> > 
> > I'm not sure I understand this:
> > > are users expecting the callbacks to run even if an error is not reported?
> > 
> > 
> > Are you referring to the `beforeNotify` and `afterNotify` callbacks? Or the `lambdaHandler` callback? I think it's OK to assume that users should not expect `beforeNotify` and `afterNotify` to be called if the report is not going to be sent. However, I think they expect the lambda handler's callback to be called in any case (report sent or not), which is what this PR is about.
> > What do you think?
> > (In any case, I will go ahead and merge this since you approved)
> 
> I was referring to the `beforeNotify` and `afterNotify` callbacks—I'm thinking about the case where a user wants to do something similar to what we're doing in `lambdaHandler`—basically "report this error, then do something else, like call a callback." That may not be a super common use case, but it would be more convenient to always call the callbacks in that case, so that the user doesn't have to add an extra conditional (like you did in this PR). 🤷

Got it. Hmm, indeed it could be a valid use case. Personally, I think it's OK as it is now, because the name `afterNotify` implies that a callback would be called _after_ Honeybadger is _notified_. However, we could provide a `reported` boolean value to the `afterNotify` callbacks that would indicate whether the error was reported or not. I'm not sure though, what do you think?

**Comment by joshuap** [comment]
> > > > This looks good to me @subzero10, thanks!
> > > > One question—do you think that we should be calling the `beforeNotify` and `afterNotify` handlers in the `Honeybadger.notify` function itself if the preconditions fail? i.e., are users expecting the callbacks to run even if an error is not reported?
> > > > I think we could ship this fix either way, I'm just curious if this is something we should revisit in the future.
> > > 
> > > 
> > > That's a good question. I think I'm leaning towards not calling them:
> > > 
> > > * If the preconditions fail -> don't call `beforeNotify` nor `afterNotify`
> > > * if `beforeNotify` returns `false` -> don't call `afterNotify`
> > > 
> > > I'm not sure I understand this:
> > > > are users expecting the callbacks to run even if an error is not reported?
> > > 
> > > 
> > > Are you referring to the `beforeNotify` and `afterNotify` callbacks? Or the `lambdaHandler` callback? I think it's OK to assume that users should not expect `beforeNotify` and `afterNotify` to be called if the report is not going to be sent. However, I think they expect the lambda handler's callback to be called in any case (report sent or not), which is what this PR is about.
> > > What do you think?
> > > (In any case, I will go ahead and merge this since you approved)
> > 
> > 
> > I was referring to the `beforeNotify` and `afterNotify` callbacks—I'm thinking about the case where a user wants to do something similar to what we're doing in `lambdaHandler`—basically "report this error, then do something else, like call a callback." That may not be a super common use case, but it would be more convenient to always call the callbacks in that case, so that the user doesn't have to add an extra conditional (like you did in this PR). 🤷
> 
> Got it. Hmm, indeed it could be a valid use case. Personally, I think it's OK as it is now, because the name `afterNotify` implies that a callback would be called _after_ Honeybadger is _notified_. However, we could provide a `reported` boolean value to the `afterNotify` callbacks that would indicate whether the error was reported or not. I'm not sure though, what do you think?

`afterNotify` already supports an optional error as the first argument—what if we just made it an error, something like `new Error('API key is not configured')`?

**Comment by subzero10** [comment]
Yeah, that could do it. Should I proceed to create a ticket and add to my backlog?

**Pull request merged**
