### PR TITLE
Workaround for Node.js-patching libraries

### PR DESCRIPTION
**Pull request by shalvah**
Workaround for [#825](https://github.com/honeybadger-io/honeybadger-js/issues/825#issuecomment-1193113433)

### CODE REVIEW

**Review by subzero10 — APPROVED** [review]
This looks harmless 😅

**Comment by subzero10** [comment]
@shipjs prepare

**Comment by subzero10** [comment]
@shalvah I cannot release a new version with this PR because it does not follow conventional commits syntax and therefore it picked up nothing to release:
```
› Calculating the next version.
The following commit messages out of convention are ignored:
  Merge pull request #843 from honeybadger-io/nodejs-patching-fix
  Workaround for Node.js-patching libraries
› Confirming the next version.
The current version: 4.0.4
The next version: 4.0.5
› Validating preparation conditions.
`shouldPrepare` returned false. So the preparation is skipped.
```
Did you not receive an error when trying to commit from your local environment? Or did you disable git hooks?
(note for me: update [this section](https://github.com/honeybadger-io/honeybadger-js#contributing) to inform about commit syntax)

I will publish a new version when [this](https://github.com/honeybadger-io/honeybadger-js/pull/845) is merged.

**Comment by shalvah** [comment]
> I cannot release a new version with this PR because it does not follow conventional commits syntax and therefore it picked up nothing to release

Isn't there a way to override it? Seems like a flaw if that can't be overridden.

> Did you not receive an error when trying to commit from your local environment

The other one did; this didn't.

**Comment by subzero10** [comment]
> > I cannot release a new version with this PR because it does not follow conventional commits syntax and therefore it picked up nothing to release
> 
> Isn't there a way to override it? Seems like a flaw if that can't be overridden.

Not from what I know. And it makes sense, because CHANGELOG is generated from the commits so they must follow the syntax. The workaround would be to push another dummy commit (new PR) with the right syntax.
> 
> > Did you not receive an error when trying to commit from your local environment
> 
> The other one did; this didn't.

This is strange. Did you pull latest before creating this branch?

**Comment by subzero10** [comment]
> The workaround would be to push another dummy commit (new PR) with the right syntax.

I will do this now so we can proceed with the release.

**Comment by subzero10** [comment]
@shipjs prepare

**Comment by subzero10** [comment]
Done! Released `v4.0.5`.

**Pull request merged**
