### PR TITLE
Add clearContext method to clear context and breadcrumbs

### PR DESCRIPTION
**Pull request by joshuap**
This should allow people to clear the context and breadcrumbs in between requests (in Express, for instance).

### CODE REVIEW

**Comment by joshuap** [comment]
I renamed the `resetContext()` method (and removed the optional argument) to be more like the Ruby client. It also felt like it was mixing responsibilities too much with the addition of breadcrumbs.

**Review by rabidpraxis — APPROVED** [review]
This all looks good to me. 

I am curious why you chose to go with `clearContext` vs a more generic `clear`? The former looks like it would not be also clearing breadcrumbs.

**Comment by joshuap** [comment]
> I am curious why you chose to go with clearContext vs a more generic clear? The former looks like it would not be also clearing breadcrumbs.

@rabidpraxis I could be talked into this. :) The reason is that in Ruby it's `Honeybadger.context.clear!`, which suffers from the same issue. I don't know... should we move towards a more standardized name for "all the session-based stuff?"

**Comment by rabidpraxis** [comment]
@joshuap My vote would for a more general name, yeah. Either way, it would be good to be consistent between languages. Also, the `clear!` method in the Ruby client is on the Agent, so the call ends up `Honeybadger.clear!`.

**Comment by joshuap** [comment]
Cool, thanks for the suggestion. I'll rename it to `Honeybadger.clear()` in JS.

**Comment by joshuap** [comment]
@shipjs prepare

**Pull request merged**
